# Generated by Django 2.2.6 on 2019-10-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='timeIntervalDay',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='timeIntervalDayTime',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='timeIntervalMinutes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='timeIntervalTime',
            field=models.CharField(default='', max_length=30),
        ),
    ]
