# Generated by Django 2.2.6 on 2019-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='url',
            field=models.TextField(max_length=256),
        ),
    ]
