# Generated by Django 2.2.6 on 2019-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0002_auto_20191009_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='messageFail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='messageSuccess',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='messageToManyFailures',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='saveResponse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='timeIntervalDay',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='timeIntervalDayTime',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='timeIntervalMinutes',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='timeIntervalTime',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='userDefined',
            field=models.BooleanField(default=False),
        ),
    ]
