# Generated by Django 2.2.6 on 2019-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0002_auto_20191008_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='messageFail',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='messageSuccess',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='messageToManyFailures',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='saveResponse',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='timeIntervalDay',
            field=models.TimeField(default=''),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='timeIntervalMinutes',
            field=models.TimeField(default=''),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='timeIntervalTime',
            field=models.TimeField(default=''),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='timeInvervalDayTime',
            field=models.TimeField(default=''),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='userDefined',
            field=models.BooleanField(default=''),
        ),
    ]
