# Generated by Django 2.2.6 on 2019-10-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0003_auto_20191009_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='userName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
