# Generated by Django 2.2.6 on 2019-10-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0003_auto_20191008_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='userName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
