# Generated by Django 2.2.6 on 2019-10-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0004_auto_20191010_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='timeIntervalDay',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='timeIntervalDayTime',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='timeIntervalMinutes',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='timeIntervalTime',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='userDefined',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='interval',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
