# Generated by Django 2.2.6 on 2019-10-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0005_auto_20191010_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='interval',
            field=models.CharField(default='default', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='url',
            field=models.URLField(default='', max_length=255, null=True),
        ),
    ]
